name: Bug Report
description: Crashes or unexpected behaviors
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        ## DankMaterialShell Bug Report
        Limit your report to one issue per submission unless closely related
  - type: checkboxes
    id: compositor
    attributes:
      label: Compositor
      options:
        - label: Niri
        - label: Hyprland
        - label: MangoWC (dwl)
        - label: Sway
    validations:
      required: true
  - type: checkboxes
    id: distribution
    attributes:
      label: Distribution
      options:
        - label: Arch Linux
        - label: CachyOS
        - label: Fedora
        - label: NixOS
        - label: Debian
        - label: Ubuntu
        - label: Gentoo
        - label: OpenSUSE
        - label: Other (specify below)
    validations:
      required: true
  - type: input
    id: distribution_other
    attributes:
      label: If Other, please specify
      placeholder: e.g., PikaOS, Void Linux, etc.
    validations:
      required: false
  - type: textarea
    id: dms_doctor
    attributes:
      label: dms doctor -v
      description: Output of `dms doctor -v` command
      placeholder: Paste the output of `dms doctor -v` here
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Brief description of the issue
      placeholder: What happened?
    validations:
      required: true
  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe the expected behavior
    validations:
      required: false
  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce & Installation Method
      description: Please provide detailed steps to reproduce the issue
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Error Messages/Logs
      description: Please include any error messages, stack traces, or relevant logs
      placeholder: |
        Paste error messages or logs here
    validations:
      required: false
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots/Recordings
      description: If applicable, add screenshots or screen recordings
      placeholder: Attach images or videos here
    validations:
      required: false
