repos:
  - repo: local
    hooks:
      - id: golangci-lint-fmt
        name: golangci-lint-fmt
        entry: go run github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.11.3 fmt
        language: system
        require_serial: true
        types: [go]
        pass_filenames: false
      - id: golangci-lint-full
        name: golangci-lint-full
        entry: go run github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.11.3 run --fix
        language: system
        require_serial: true
        types: [go]
        pass_filenames: false
      - id: golangci-lint-config-verify
        name: golangci-lint-config-verify
        entry: go run github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.11.3 config verify
        language: system
        files: \.golangci\.(?:yml|yaml|toml|json)
        pass_filenames: false
      - id: go-test
        name: go test
        entry: go test ./...
        language: system
        pass_filenames: false
        types: [go]
